version: "3"
services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mohit0205
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=my_database
      - SECRET_KEY=your_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mohit0205
      - MYSQL_DATABASE=my_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: